name: Build and Push Dev Docker Images for tagged versions

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up metadata
        id: meta
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/api.Dockerfile
          # Only push when not a PR
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${ { toLower(github.repository_owner) }}/agent_c_api_dev:latest
            ghcr.io/${ { toLower(github.repository_owner) }}/agent_c_api_dev:build-${{ github.run_number }}
            ghcr.io/${ { toLower(github.repository_owner) }}/agent_c_api_dev:${{ env.SHORT_SHA }}
            ghcr.io/${ { toLower(github.repository_owner) }}/agent_c_api_dev:${{ env.DATE }}

      - name: Build and push Framework image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/Dockerfile.dev
          # Only push when not a PR
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${ { toLower(github.repository_owner) }}/agent_c_framework_dev:latest
            ghcr.io/${ { toLower(github.repository_owner) }}/agent_c_framework_dev:build-${{ github.run_number }}
            ghcr.io/${ { toLower(github.repository_owner) }}/agent_c_framework_dev:${{ env.SHORT_SHA }}
            ghcr.io/${ { toLower(github.repository_owner) }}/agent_c_framework_dev:${{ env.DATE }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/frontend.Dockerfile
          # Only push when not a PR
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${ { toLower(github.repository_owner) }}/agent_c_frontend_dev:latest
            ghcr.io/${ { toLower(github.repository_owner) }}/agent_c_frontend_dev:build-${{ github.run_number }}
            ghcr.io/${ { toLower(github.repository_owner) }}/agent_c_frontend_dev:${{ env.SHORT_SHA }}
            ghcr.io/${ { toLower(github.repository_owner) }}/agent_c_frontend_dev:${{ env.DATE }}
